package view;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Usuário
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLogoInicio = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuInicio = new javax.swing.JMenu();
        jMenuItemInicio = new javax.swing.JMenuItem();
        jMenuUsuarios = new javax.swing.JMenu();
        jMenuItemCadastroUsuarios = new javax.swing.JMenuItem();
        jMenuItemListagemUsuarios = new javax.swing.JMenuItem();
        jMenuAnimais = new javax.swing.JMenu();
        jMenuItemAnimais = new javax.swing.JMenuItem();
        jMenuTratamentos = new javax.swing.JMenu();
        jMenuItemCadastroTratamento = new javax.swing.JMenuItem();
        jMenuItemListagemTratamentos = new javax.swing.JMenuItem();
        jMenuProdutos = new javax.swing.JMenu();
        jMenuItemCadastroProdutos = new javax.swing.JMenuItem();
        jMenuItemListagemProdutos = new javax.swing.JMenuItem();
        jMenuServiços = new javax.swing.JMenu();
        jMenuItemCadastroServicos = new javax.swing.JMenuItem();
        jMenuItemListagemServicos = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabelLogoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        getContentPane().add(jLabelLogoInicio);
        jLabelLogoInicio.setBounds(40, 40, 260, 240);

        jMenuInicio.setText("Inicio");

        jMenuItemInicio.setText("Inicio");
        jMenuItemInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInicioActionPerformed(evt);
            }
        });
        jMenuInicio.add(jMenuItemInicio);

        jMenuBar1.add(jMenuInicio);

        jMenuUsuarios.setText("Usuarios");

        jMenuItemCadastroUsuarios.setText("Cadastro");
        jMenuItemCadastroUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroUsuariosActionPerformed(evt);
            }
        });
        jMenuUsuarios.add(jMenuItemCadastroUsuarios);

        jMenuItemListagemUsuarios.setText("Listagem");
        jMenuItemListagemUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListagemUsuariosActionPerformed(evt);
            }
        });
        jMenuUsuarios.add(jMenuItemListagemUsuarios);

        jMenuBar1.add(jMenuUsuarios);

        jMenuAnimais.setText("Animais");

        jMenuItemAnimais.setText("Animais");
        jMenuItemAnimais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAnimaisActionPerformed(evt);
            }
        });
        jMenuAnimais.add(jMenuItemAnimais);

        jMenuBar1.add(jMenuAnimais);

        jMenuTratamentos.setText("Tratamentos");

        jMenuItemCadastroTratamento.setText("Cadastro");
        jMenuItemCadastroTratamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroTratamentoActionPerformed(evt);
            }
        });
        jMenuTratamentos.add(jMenuItemCadastroTratamento);

        jMenuItemListagemTratamentos.setText("Listagem");
        jMenuItemListagemTratamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListagemTratamentosActionPerformed(evt);
            }
        });
        jMenuTratamentos.add(jMenuItemListagemTratamentos);

        jMenuBar1.add(jMenuTratamentos);

        jMenuProdutos.setText("Produtos");

        jMenuItemCadastroProdutos.setText("Cadastro");
        jMenuItemCadastroProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroProdutosActionPerformed(evt);
            }
        });
        jMenuProdutos.add(jMenuItemCadastroProdutos);

        jMenuItemListagemProdutos.setText("Listagem");
        jMenuItemListagemProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListagemProdutosActionPerformed(evt);
            }
        });
        jMenuProdutos.add(jMenuItemListagemProdutos);

        jMenuBar1.add(jMenuProdutos);

        jMenuServiços.setText("Serviços");

        jMenuItemCadastroServicos.setText("Cadastro");
        jMenuItemCadastroServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroServicosActionPerformed(evt);
            }
        });
        jMenuServiços.add(jMenuItemCadastroServicos);

        jMenuItemListagemServicos.setText("Listagem");
        jMenuItemListagemServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListagemServicosActionPerformed(evt);
            }
        });
        jMenuServiços.add(jMenuItemListagemServicos);

        jMenuBar1.add(jMenuServiços);

        jMenuSair.setText("Sair");

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemSair);

        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(644, 385));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadastroUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemCadastroUsuariosActionPerformed

    private void jMenuItemCadastroServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroServicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemCadastroServicosActionPerformed

    private void jMenuItemCadastroProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroProdutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemCadastroProdutosActionPerformed

    private void jMenuItemListagemProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListagemProdutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemListagemProdutosActionPerformed

    private void jMenuItemListagemServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListagemServicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemListagemServicosActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemListagemUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListagemUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemListagemUsuariosActionPerformed

    private void jMenuItemAnimaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAnimaisActionPerformed
        TelaAnimal cadastro = new TelaAnimal();
        cadastro.setVisible(true);
        dispose();
        
        
    }//GEN-LAST:event_jMenuItemAnimaisActionPerformed

    private void jMenuItemCadastroTratamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroTratamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemCadastroTratamentoActionPerformed

    private void jMenuItemListagemTratamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListagemTratamentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemListagemTratamentosActionPerformed

    private void jMenuItemInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInicioActionPerformed
        TelaPrincipal tela = new TelaPrincipal();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemInicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelLogoInicio;
    private javax.swing.JMenu jMenuAnimais;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuInicio;
    private javax.swing.JMenuItem jMenuItemAnimais;
    private javax.swing.JMenuItem jMenuItemCadastroProdutos;
    private javax.swing.JMenuItem jMenuItemCadastroServicos;
    private javax.swing.JMenuItem jMenuItemCadastroTratamento;
    private javax.swing.JMenuItem jMenuItemCadastroUsuarios;
    private javax.swing.JMenuItem jMenuItemInicio;
    private javax.swing.JMenuItem jMenuItemListagemProdutos;
    private javax.swing.JMenuItem jMenuItemListagemServicos;
    private javax.swing.JMenuItem jMenuItemListagemTratamentos;
    private javax.swing.JMenuItem jMenuItemListagemUsuarios;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenu jMenuProdutos;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JMenu jMenuServiços;
    private javax.swing.JMenu jMenuTratamentos;
    private javax.swing.JMenu jMenuUsuarios;
    // End of variables declaration//GEN-END:variables
}
